[package]
name = "npax"
version = "0.2.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
platform-dirs = "0.3.0"
toml = "0.8.8"
serde_json = "1.0.108"
python-input = "0.8.0"
