name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore cache
      uses: actions/cache/restore@v3
      with:
        path: target
        key: buildtest-target-cache
    - name: Build
      run: cargo build
    - name: Update cache
      uses: actions/cache/save@v3
      with:
        path: target
        key: buildtest-target-cache
    - name: Run unit tests
      run: cargo test
